// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmrxuhdaoichbxuqgmvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtcnh1aGRhb2ljaGJ4dXFnbXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Nzc0OTAsImV4cCI6MjA2MDU1MzQ5MH0.SXcEynNWaEPDVZuP4c-lop9_PVD7WvkUArzqjkKQets";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);